# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.cache/wt [current_project]
set_property parent.project_path C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/scoreby7seg.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/Move_ball.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/draw.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/Collision.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/Move_rac.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/divider.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/displaytest.v
  C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/sources_1/new/Top.v
}
read_xdc C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/constrs_1/imports/CPE222/Project_1xdc.xdc
set_property used_in_implementation false [get_files C:/Users/Dr804t/Documents/CPE222/pong_4/Pong.srcs/constrs_1/imports/CPE222/Project_1xdc.xdc]

synth_design -top Top -part xc7a35tcpg236-1
write_checkpoint -noxdef Top.dcp
catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
